### ISSUE TITLE
emoji_id returns {"error":"Unauthorized: Missing auth token"}

### ISSUE THREAD

**Issue by z0rg0n** [z0rg0n/multiyat#1]
I want to send this to get the list of yats I own:
`get(base_url + '/emoji_id', headers=headers`

But whatever header I send I get returned:
**{"error":"Unauthorized: Missing auth token"}**
  
I've tried sending these headers:
```
   {'Content-Type': 'application/json',
    'X-Api-Key': "{'api_key': '214_MRKQ... ...76Z'}",
    'access_token': 'eyJ... ...Jgk',
    'refresh_token': 'eyJ0... ...dyiM'}
```
```
   {'Content-Type': 'application/json',
    'X-Api-Key': "{'api_key': '214_MRKQ... ...76Z'}",
    'access_token': 'eyJ... ...Jgk',
```
```
   {'Content-Type': 'application/json',
    'X-Api-Key': "{'api_key': '214_MRKQ... ...76Z'}",
    'refresh_token': 'eyJ0... ...dyiM'}
```
and
```
   {'Content-Type': 'application/json',
    'X-Api-Key': "{'api_key': '214_MRKQ... ...76Z'}",
```
 
 
Headers are created in credentials.create_xapi_head() and credentials.create_yapi_head()
One of these creates a head with an x-api-key and the other creates one with the access and refresh tokens
  
I think the x-api-head key I'm sending should work because when refreshing the 2fa with the created x-api-head I get returned:
> 'requires_2fa': None, 'has_password': True
(Along with an 'access_token' and 'refresh_token')

So I think 2fa is all set and x-api-key works.

The access token and refresh token received here are used in redentials.create_yapi_head()

**Comment by z0rg0n** [comment]
My best guess is

**Comment by z0rg0n** [comment]
It turns out that the 'Authorization' header is needed.
This is the same header used to get the API key.

**Comment by Krakaw** [comment]
The `Authorization` header is only needed to get the `X-Api-Key` the formatting is wrong in your header, It should be:
```json
{
  'Content-Type': 'application/json',
  'X-Api-Key':  '214_MRKQ... ...76Z'
}
```

**Comment by z0rg0n** [comment]
Wow. Not understanding that the 'X-Api-Key' I was supposed to send was **only** the part of the response that was labeled 'api_key' is so obvious now.

I've been getting by using the authorization token in 15 minute bursts like a fool.
